# Generated by Django 5.0.2 on 2024-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
