# Generated by Django 5.0.2 on 2024-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contactmessage_alter_movie_movie_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('about_paragraph', models.TextField(max_length=1000)),
                ('mission', models.CharField(max_length=255)),
            ],
        ),
    ]
